version: '3'

services:

  back:
    container_name: "back"
    build: ./testapp
    ports:
      - "3000"
    depends_on:
      - postg
    restart: always

  front:
    container_name: "front"
    build: ./testContainerAngular
    ports:
      - "4200"
    depends_on:
      - back
    restart: always

  postg:
    container_name: "postg"
    image: postgres:9.6
    ports:
        - "5432"
    volumes:
          - ./local/postgres:/var/lib/postgresql/data
    restart: always

  nginx:
    container_name: "nginx"
    build: ./nginx
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - front
    restart: always