apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: front
  name: front
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 15
  template:
    metadata:
      labels:
        service: front
    spec:
      containers:
      - name: front
        image: xscreamjkee/front
        ports:
        - containerPort: 4200
#      nodeSelector:
#        label: node1
      restartPolicy: Always
