apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: postgres
  name: postg
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        service: postgres
    spec:
      containers:
      - name: postg
        image: amsterdam/postgres9.6
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /postg
          name: postg-volume
      volumes:
      - name: postg-volume
        hostPath:
          path: "/local/postgres"
#      nodeSelector:
#        label: node1
      restartPolicy: Always
