apiVersion: v1
kind: Service
metadata:
  labels:
    service: nginx
  name: nginx
spec:
  type: NodePort
  ports:
  - name: "nginx-front"
    port: 80
    targetPort: 80
    nodePort: 30004
  - name: "nginx-back"
    port: 8080
    targetPort: 8080
    nodePort: 30005
  selector:
    service: nginx
