---
- name: Install docker | software
  apt:  
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
     - apt-transport-https
     - ca-certificates
     - curl
     - software-properties-common


- name: Add docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present


- name: Key with the fingerprint
  apt_key:
    id: 0EBFCD88
    state: present

- name: Add docker repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: Install docker
  apt:
    name: docker-ce
    state: installed
    update_cache: yes